### ISSUE TITLE
Question about results on IEMOCAP

### ISSUE THREAD

**Issue by deepsuperviser** [zlwang-cs/TransModality#3]
Hey!
This is an interesting work.
However, the baselines mentioned in your paper "TransModality: An End2End Fusion Method with Transformer for Multimodal Sentiment Analysis" don't verify their models on the dataset IEMOCAP. Where are the resullts in Table 3 from?

Besides, 6 emotion labels is used for classification in your paper. However, there is 7 labels in your code. Which is True.

We really need the details of your used IEMOCAP. (We know that "As for the features, we used the features offered in project: https://github.com/soujanyaporia/multimodal-sentiment-analysis and project: https://github.com/soujanyaporia/contextual-multimodal-fusion. Please download features there.")

**Comment by zlwang-cs** [comment]
Thanks for your interests of our projects!

The results in our paper is based on our experiments on the corresponding dataset and models. As for the number of labels, we find there is a typo in our code. The MELD-emotion dataset actually has 7 labels while IEMOCAP has 6 labels. Sorry for the confusion.

**Comment by deepsuperviser** [comment]
thank you for your reply.
Please ensure that your experiments on the corresponding dataset and models and the results in your paper is real.

Please ensure that the codes released are consistent with your experiments (because there is typos in your code).
